# Generated by Django 3.2.5 on 2021-08-11 11:03

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filmwork",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="создано",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="обновлено в последний раз",
                    ),
                ),
                ("title", models.CharField(max_length=254, verbose_name="название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="описание"),
                ),
                (
                    "creation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата создания фильма"
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="рейтинг",
                    ),
                ),
                (
                    "mpaa_age_rating",
                    models.CharField(
                        choices=[
                            ("general", "без ограничений"),
                            (
                                "parental_guidance",
                                "рекомендовано смотреть с родителями",
                            ),
                            (
                                "parental_guidance_strong",
                                "просмотр не желателен детям до 13 лет",
                            ),
                            ("restricted", "до 17 в сопровождении родителей"),
                            ("no_one_17_under", "только с 18"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="возрастной рейтинг",
                    ),
                ),
                (
                    "imdb_rating",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="рейтинг",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True, upload_to="film_works", verbose_name="файл"
                    ),
                ),
            ],
            options={
                "verbose_name": "кинопроизведение",
                "verbose_name_plural": "кинопроизведения",
                "db_table": "film_work",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="создано",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="обновлено в последний раз",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="описание"),
                ),
            ],
            options={
                "verbose_name": "жанр",
                "verbose_name_plural": "жанры",
                "db_table": "genre",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="создано",
                    ),
                ),
                (
                    "updated_at",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="обновлено в последний раз",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="имя")),
            ],
            options={
                "verbose_name": "персона",
                "verbose_name_plural": "персоны",
                "db_table": "person",
            },
        ),
        migrations.CreateModel(
            name="FilmWorkPerson",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ACTOR", "актер"),
                            ("WRITER", "сценарист"),
                            ("DIRECTOR", "режиссер"),
                        ],
                        max_length=255,
                        verbose_name="профессия",
                    ),
                ),
                (
                    "film_work_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.filmwork",
                        verbose_name="фильм",
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.person",
                        verbose_name="человек",
                    ),
                ),
            ],
            options={
                "verbose_name": "участник фильма",
                "verbose_name_plural": "участники фильмов",
                "db_table": "film_work_person",
                "unique_together": {("film_work_id", "person_id", "role")},
            },
        ),
        migrations.CreateModel(
            name="FilmWorkGenre",
            fields=[
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "film_work_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.filmwork",
                        verbose_name="фильм",
                    ),
                ),
                (
                    "genre_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.genre",
                        verbose_name="жанр",
                    ),
                ),
            ],
            options={
                "verbose_name": "жанр",
                "verbose_name_plural": "жанры",
                "db_table": "film_work_genre",
                "unique_together": {("film_work_id", "genre_id")},
            },
        ),
        migrations.AddField(
            model_name="filmwork",
            name="genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="film_works",
                through="movies.FilmWorkGenre",
                to="movies.Genre",
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                blank=True,
                related_name="film_works",
                through="movies.FilmWorkPerson",
                to="movies.Person",
            ),
        ),
    ]
