# Generated by Django 3.2.5 on 2021-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="type",
            field=models.CharField(
                choices=[
                    ("MOVIE", "фильм"),
                    ("SERIES", "сериал"),
                    ("TV_SHOW", "тв шоу"),
                ],
                default="MOVIE",
                max_length=20,
                verbose_name="тип",
            ),
        ),
    ]
