# Generated by Django 3.2.5 on 2021-08-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_filmwork_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filmworkgenre",
            old_name="film_work_id",
            new_name="film_work",
        ),
        migrations.RenameField(
            model_name="filmworkgenre",
            old_name="genre_id",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="filmworkperson",
            old_name="film_work_id",
            new_name="film_work",
        ),
        migrations.RenameField(
            model_name="filmworkperson",
            old_name="person_id",
            new_name="person",
        ),
    ]
